### PR TITLE
Update to KF5.45

### PR DESCRIPTION
**Pull request by lnjX**

### CODE REVIEW

**Comment by azubieta** [comment]
It's Ok to me. I just would like to keep the previous release for compatibility reasons and to not force the update in the client scripts.

**Review by azubieta — APPROVED** [review]

**Comment by lnjX** [comment]
I also thought about this. We somehow need branches or tags to fix this, but I assume that you agree merging this, though.

Btw, I somehow forgot to invite you to this repo: https://github.com/kf5builds/precompiled-kf5-linux/invitations.

**Comment by azubieta** [comment]
I think that using tags will be enough in order to keep version control. I already moved the 5.44 binaries to the 5.44 release so the continuous tag can be safely overridden.
Also if you want you can create a new tag and release for the 5.45

**Comment by lnjX** [comment]
@azubieta I think you can merge this (self merging isn't that nice). :)

**Comment by lnjX** [comment]
Thanks :)

Just for the next time: I personally prefer to use Squash and merge for merging, this will then create a single commit. Would be nice if you could use that. :smiley:

**Comment by azubieta** [comment]
I didn't want to override your name from the commit. But is ok if you wan't it that way.

**Pull request merged**
